name: Robo de Cobranca Diaria

on:
  schedule:
    # Roda todo dia às 09:00 (Horário de Brasília)
    - cron: '0 12 * * *'
  workflow_dispatch: # Permite testar manualmente

jobs:
  executar_job:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando os arquivos
        uses: actions/checkout@v3

      - name: Instalando Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalando bibliotecas
        run: pip install supabase requests

      - name: Rodando o Robo
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          API_WHATSAPP_URL: ${{ secrets.API_WHATSAPP_URL }}
          API_WHATSAPP_KEY: ${{ secrets.API_WHATSAPP_KEY }}
        run: python robo_cobranca.py
        
